services:
  db:
    image: postgres:16
    container_name: config-and-ff-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: config-and-feature-flag-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdocker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d config-and-feature-flag-service"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db-data:
